### ISSUE TITLE
preserve existing IDs

### ISSUE THREAD

**Issue by pkra** [krautzource/sre-to-tree#11]
A node might already have an id (which might be referenced from elsewhere).  Do we preserve such IDs?

**Comment by pkra** [comment]
> Do we preserve such IDs?

No, we do not. But we should.

**Comment by pkra** [comment]
Not sure if SRE is a better place for this - ping @zorkow, what do you think?

**Comment by zorkow** [comment]
SRE should not be overwriting ids. Semantic ids are stored elsewhere, not in the `id` attribute.
In principle, all the attributes that are in the incoming structure should also be in the enriched structure. Where do you see this?

**Comment by pkra** [comment]
Thanks @zorkow and apologies for creating confusion. 

SRE is not doing anything wrong, sre-to-tree is. 

sre-to-tree currently writes over pre-existing IDs with the IDs it generates from data-semantic-id. Stopping that is easy, but now sre-to-tree needs to rewrite the aria-owns properties of their semantic parents.

While I don't think it makes sense for SRE to consider re-using pre-existing ids as data-semantic ids, I thought I'd better double check with you.

**Comment by pkra** [comment]
> While I don't think it makes sense for SRE to consider re-using pre-existing ids as data-semantic ids, I thought I'd better double check with you.

To expand slightly: if SRE re-used pre-existing IDs as data-semantic-id, then the data-semantic-owns would already have the "correct" id so sre-to-tree just had to not overwrite it. But I suspect it's just overhead for SRE without anything to gain from SRE's point of view.

**Comment by pkra** [comment]
I have a preliminary implementation that needs more testing.

**Comment by zorkow** [comment]
> > While I don't think it makes sense for SRE to consider re-using pre-existing ids as data-semantic ids, I thought I'd better double check with you.
> 
> To expand slightly: if SRE re-used pre-existing IDs as data-semantic-id, then the data-semantic-owns would already have the "correct" id so sre-to-tree just had to not overwrite it. But I suspect it's just overhead for SRE without anything to gain from SRE's point of view.

Not a good idea. The semantic tree is constructed with minimal reference to the incoming structure. Original attributes are preserved via folding the tree back into the original structure. So trying to reuse ids while the tree is constructed is not practical. Also it would conflate concerns.

The only mechanism would be to mark up leaf nodes. The `ext-id` mechanism we use for MathLive is an example. But in general I think this should be done by the caller.

**Comment by zorkow** [comment]
> I have a preliminary implementation that needs more testing.

Is that in `master`?

**Comment by pkra** [comment]
> The only mechanism would be to mark up leaf nodes. The ext-id mechanism we use for MathLive is an example. But in general I think this should be done by the caller.

Thanks for confirming.

> Is that in master?

Not yet.
